# Generated by Django 2.0 on 2017-12-17 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20171210_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('hospital', models.CharField(max_length=50)),
                ('login', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
